/*
Helga Hjartardóttir 
helgahja@gmail.com 
8. febrúar 2015
Yahtzee15 er einfaldur yahtzee leikur með þremur teningum. 
Maður kastar einu sinni, skráir stig og heldur þannig áfram þar til leikurinn 
klárast og þá safnar maður saman lokastigum. 
Notast var við NetBeans til að þýða og þjappa forritið. 
*/
 
package yahtzee15;

import javax.swing.JButton;

/**
 *
 * @author helgah
 */

//YahzeeUtlit geymir viðmótshluta forritsins        
public class YahtzeeUtlit extends javax.swing.JFrame {

    /**
     * Creates new form Yahtzee15
     */
    //Býr til YahtzeeUtlit. 
    public YahtzeeUtlit() {
        initComponents();
    }
    
    public boolean kasta = true; //setur boolean gildi fyrir kast. 
    public YahtzeeLeikur leikur = new YahtzeeLeikur(); //býr til nýjan YahzeeLeikur. 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kastaTakki = new javax.swing.JButton();
        teningur1 = new javax.swing.JLabel();
        teningur2 = new javax.swing.JLabel();
        teningur3 = new javax.swing.JLabel();
        skra1 = new javax.swing.JButton();
        skra2 = new javax.swing.JButton();
        skra3 = new javax.swing.JButton();
        skra4 = new javax.swing.JButton();
        skra5 = new javax.swing.JButton();
        skra6 = new javax.swing.JButton();
        skraSens = new javax.swing.JButton();
        skraYahtzee = new javax.swing.JButton();
        stig1 = new javax.swing.JTextField();
        stig2 = new javax.swing.JTextField();
        stig3 = new javax.swing.JTextField();
        stig4 = new javax.swing.JTextField();
        stig5 = new javax.swing.JTextField();
        stig6 = new javax.swing.JTextField();
        stigSens = new javax.swing.JTextField();
        stigYahtzee = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        nyrLeikurTakki = new javax.swing.JButton();
        nidurstodurTakki = new javax.swing.JButton();
        nidurstodur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(544, 599));
        setResizable(false);

        kastaTakki.setFont(new java.awt.Font("Lucida Console", 0, 15)); // NOI18N
        kastaTakki.setText("Kasta teningum");
        kastaTakki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kastaTeningum(evt);
            }
        });

        teningur1.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        teningur1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        teningur1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yahtzee15/1.png"))); // NOI18N

        teningur2.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        teningur2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teningur2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yahtzee15/2.png"))); // NOI18N

        teningur3.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        teningur3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yahtzee15/3.png"))); // NOI18N

        skra1.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        skra1.setName("skra1");
        skra1.setText("Ásar");
        skra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraStig(evt);
            }
        });

        skra2.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        skra2.setName("skra2");
        skra2.setText("Tvistar");
        skra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraStig(evt);
            }
        });

        skra3.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        skra3.setName("skra3");
        skra3.setText("Þristar");
        skra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraStig(evt);
            }
        });

        skra4.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        skra4.setName("skra4");
        skra4.setText("Fjarkar");
        skra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraStig(evt);
            }
        });

        skra5.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        skra5.setName("skra5");
        skra5.setText("Fimmur");
        skra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraStig(evt);
            }
        });

        skra6.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        skra6.setName("skra6");
        skra6.setText("Sexur");
        skra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraStig(evt);
            }
        });

        skraSens.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        skraSens.setName("skraSens");
        skraSens.setText("Taka séns");
        skraSens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraStig(evt);
            }
        });

        skraYahtzee.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        skraYahtzee.setName("skraYahtzee");
        skraYahtzee.setText("Yahtzee");
        skraYahtzee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraStig(evt);
            }
        });

        stig1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stig1.setFocusable(false);
        stig1.setSize(new java.awt.Dimension(84, 28));

        stig2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stig2.setFocusable(false);
        stig2.setSize(new java.awt.Dimension(84, 28));

        stig3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stig3.setFocusable(false);
        stig3.setSize(new java.awt.Dimension(84, 28));

        stig4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stig4.setFocusable(false);
        stig4.setSize(new java.awt.Dimension(84, 28));

        stig5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stig5.setFocusable(false);
        stig5.setSize(new java.awt.Dimension(84, 28));

        stig6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stig6.setFocusable(false);
        stig6.setSize(new java.awt.Dimension(84, 28));

        stigSens.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stigSens.setFocusable(false);
        stigSens.setSize(new java.awt.Dimension(84, 28));

        stigYahtzee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stigYahtzee.setFocusable(false);
        stigYahtzee.setSize(new java.awt.Dimension(84, 28));

        jLabel4.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("    YAHTZEE");

        nyrLeikurTakki.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        nyrLeikurTakki.setText("Nýr leikur");
        nyrLeikurTakki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyrLeikur(evt);
            }
        });

        nidurstodurTakki.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        nidurstodurTakki.setText("Niðurstöður");
        nidurstodurTakki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nidurstodur(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(nyrLeikurTakki, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(nidurstodurTakki, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nidurstodurTakki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nyrLeikurTakki))
                .addGap(19, 19, 19))
        );

        nidurstodur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nidurstodur.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(nidurstodur, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skra4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skra5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skra6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skraYahtzee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skraSens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stig1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stig2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stig3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stig4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stig5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stig6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stigSens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stigYahtzee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teningur1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 425, Short.MAX_VALUE))
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(teningur2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(teningur3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(kastaTakki, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kastaTakki, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teningur1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teningur2)
                    .addComponent(teningur3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(skra1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stig2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(skra2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stig3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(skra3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stig4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(skra4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stig5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(skra5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stig6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(skra6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stigSens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(skraSens)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stigYahtzee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skraYahtzee, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nidurstodur, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void synaKast(javax.swing.JLabel TeningurX, int val) 
    {
        switch(val){
            case 1: TeningurX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yahtzee15/1.png")));
                break;
            case 2: TeningurX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yahtzee15/2.png")));
                break;
            case 3: TeningurX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yahtzee15/3.png")));
                break;
            case 4: TeningurX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yahtzee15/4.png")));
                break;
            case 5: TeningurX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yahtzee15/5.png")));
                break;
            case 6: TeningurX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yahtzee15/6.png")));
                break;
        }
    }
    //KastaTeningum les inn gildi teningsins eftir að kastað hefur verið
    private void kastaTeningum(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kastaTeningum
        // TODO add your handling code here:
        
        if (kasta){
            
        leikur.kastaTeningum();
        synaKast(teningur1, leikur.teningar[0].lesaGildi()); 
        synaKast(teningur2, leikur.teningar[1].lesaGildi());
        synaKast(teningur3, leikur.teningar[2].lesaGildi());
        kasta = false;
        }
        else {
        new Vidvorun().setVisible(true);
        }
    }//GEN-LAST:event_kastaTeningum
    //greinaTakka greinir töluna sem teningurinn gefur.
    private String greinaTakka(java.awt.event.ActionEvent evt) {
        JButton CurrentButton = (JButton) evt.getSource();
        String tempString = CurrentButton.getName();
        String ret = tempString.substring(4);
        CurrentButton.setEnabled(false);
        return ret;
    }
    // skraStig skrárir inn stigin sem koma úr hverju kasti. 
    private void skraStig(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skraStig
        if (kasta == false)
        {
            String x = greinaTakka(evt);
            int sum = 0;
            if (x.equals("Sens")) 
            {
                sum = leikur.teningar[0].lesaGildi() + leikur.teningar[1].lesaGildi() + leikur.teningar[2].lesaGildi();
                stigSens.setText(Integer.toString(sum));
                leikur.yahtzeeBlad.setjaToluIReit(6, sum);
                kasta = true;
            }    
            else if (x.equals("Yahtzee"))
            {
                if (leikur.teningar[0].lesaGildi() == leikur.teningar[1].lesaGildi() && leikur.teningar[0].lesaGildi() == leikur.teningar[2].lesaGildi())
                {
                    stigYahtzee.setText("50");
                    leikur.yahtzeeBlad.setjaToluIReit(7, 50);
                }
                else stigYahtzee.setText("0");
                kasta = true;
                
            }
            else {
                for (int i=0; i<3; i++) 
                {
                    if (leikur.teningar[i].lesaGildi() == Integer.parseInt(x))
                        sum+=leikur.teningar[i].lesaGildi();
                }
                leikur.yahtzeeBlad.setjaToluIReit(Integer.parseInt(x)-1, sum);
                switch(Integer.parseInt(x)) 
                {
                    case 1 : stig1.setText(Integer.toString(sum));
                        break;
                    case 2 : stig2.setText(Integer.toString(sum));  
                        break;
                    case 3 : stig3.setText(Integer.toString(sum));
                        break;
                    case 4 : stig4.setText(Integer.toString(sum));
                        break;
                    case 5 : stig5.setText(Integer.toString(sum));
                        break;
                    case 6 : stig6.setText(Integer.toString(sum));
                }
                kasta = true;
            }
        }
    }//GEN-LAST:event_skraStig
    // nidurstodur tekur saman nidurstöður kastannna. 
    private void nidurstodur(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nidurstodur
        // TODO add your handling code here:
        nidurstodur.setText(Integer.toString(leikur.yahtzeeBlad.nidurstada()));
        
        
    }//GEN-LAST:event_nidurstodur
    //nyrLeikur endurræsir leikinn. 
    private void nyrLeikur(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyrLeikur
       
        if (evt.getSource() == nyrLeikurTakki)
        {
            leikur = new YahtzeeLeikur(); 
            this.dispose();
            new YahtzeeUtlit().setVisible(true);
        }
        
    }//GEN-LAST:event_nyrLeikur

    /**
     * @param args the command line arguments
     */
    //main fallið keyrir YahzeeUtlit gluggann. 
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YahtzeeUtlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YahtzeeUtlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YahtzeeUtlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YahtzeeUtlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YahtzeeUtlit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton kastaTakki;
    private javax.swing.JTextField nidurstodur;
    private javax.swing.JButton nidurstodurTakki;
    private javax.swing.JButton nyrLeikurTakki;
    private javax.swing.JButton skra1;
    private javax.swing.JButton skra2;
    private javax.swing.JButton skra3;
    private javax.swing.JButton skra4;
    private javax.swing.JButton skra5;
    private javax.swing.JButton skra6;
    private javax.swing.JButton skraSens;
    private javax.swing.JButton skraYahtzee;
    private javax.swing.JTextField stig1;
    private javax.swing.JTextField stig2;
    private javax.swing.JTextField stig3;
    private javax.swing.JTextField stig4;
    private javax.swing.JTextField stig5;
    private javax.swing.JTextField stig6;
    private javax.swing.JTextField stigSens;
    private javax.swing.JTextField stigYahtzee;
    private javax.swing.JLabel teningur1;
    private javax.swing.JLabel teningur2;
    private javax.swing.JLabel teningur3;
    // End of variables declaration//GEN-END:variables
}
